#!/bin/zsh

alias gccx="gcc -Wall -Wextra -Werror"
alias browse="explorer.exe"

alias ga="git add "
alias gaA="git add -A"
alias gcm="git commit -m "

alias python="python3.9"
alias pip="pip3"

alias rmx='\rm'
alias rm='echo "You should use trash-put (trm) command instead of rm."; false'
alias trm="trash-put"

alias open="xdg-open"
alias gittree='git log --graph --all --format="%x09%C(cyan bold)%an%Creset%x09%C(yellow)%h%Creset %C(magenta reverse)%d%Creset %s"'

alias here="gnome-terminal"
alias clipcopy='xsel --clipboard --input'

alias mv='mv -i'
alias cp='cp -i'

alias sudo='sudo '
alias tsnode='npx ts-node'
alias sl=ls

alias ls='ls --color=auto'
alias grep='grep --color=auto'
alias vzsh='vim ~/.zshrc'
alias szsh='source ~/.zshrc'
alias mon2cam="deno run --unstable -A -r -q https://raw.githubusercontent.com/ShayBox/Mon2Cam/master/src/mod.ts"

alias win_switch="${HOME}/work/win_switch/win_switch.sh"
alias plantuml-server="docker run -d -p 8080:8080 plantuml/plantuml-server:jetty"
alias clangx="clang++ -Wall -Wextra -Werror"
alias til="code ~/work/TIL"
alias valgrind="colour-valgrind"
alias bat="batcat"

if [[ -x `which colordiff` ]]; then
  alias diff='colordiff'
fi

alias sail="./vendor/bin/sail"
