#!/bin/zsh

#export DISPLAY=$(cat /etc/resolv.conf | grep nameserver | awk '{print $2}'):0.0
export USER=rnakai
export MAIL=$USER@student.42tokyo.jp
export PATH="${HOME}/.local/lib/go/bin:${PATH}"
export PATH="${HOME}/go/bin:${PATH}"
export PATH=/home/rnakai/.tiup/bin:$PATH
export PATH="$PATH:/home/rnakai/.local/bin"
export PATH="$PATH:/home/rnakai/.asdf/installs/nodejs/22.21.0/bin"

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8

export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
